### PR TITLE
Create Hydration Monitoring

### PR DESCRIPTION
**Pull request by Gmaya317**

### CODE REVIEW

**Comment by Gmaya317** [comment]
[activity_environment_data.csv](https://github.com/jiahaowang0906/Redback_Project2_wearable-tech-sensors/files/13613430/activity_environment_data.csv)
[digital_interaction_data.csv](https://github.com/jiahaowang0906/Redback_Project2_wearable-tech-sensors/files/13613431/digital_interaction_data.csv)
[personal_health_data.csv](https://github.com/jiahaowang0906/Redback_Project2_wearable-tech-sensors/files/13613432/personal_health_data.csv)


Updating DataSet

**Comment by Gmaya317** [comment]
!python -m pip install "pymongo[srv]"==3.10

!python -m pip install thingspeak pymongo

import time
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pymongo import MongoClient

# ThingSpeak Channel Setup
channel_id = 2358594  # ThingSpeak channel ID
read_api_key = 'V36WZ1G9MNX31L8D'  # ThingSpeak Read API key

# MongoDB Connection Setup
uri = "mongodb+srv://luziferzacks:FH6c9Xws94Mwf4Zs@clustersmarthydration.pjdxymt.mongodb.net/?retryWrites=true&w=majority"

# Establishing a connection to MongoDB
client = MongoClient(uri)
db = client['HydrationMonitoring']  # Database name
collection = db['SensorData']  # Collection name

print("MongoDB Connected Successfully")

# Function to fetch hydration data from ThingSpeak
def fetch_sensor_data():
    url = f'https://api.thingspeak.com/channels/{channel_id}/feeds.json?api_key={read_api_key}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()['feeds']
        # Remap data to descriptive column names
        remapped_data = [
            {
                "Hydration Level": d["field1"],
                "Ambient Temperature": d["field2"],
                "Heart Rate": d["field3"],
                "Activity Level": d["field4"],
                "Skin Temperature": d["field5"],
                "Environmental Humidity": d["field6"],
                "Fluid Intake": d["field7"],
                "Weight": d["field8"],
                "created_at": d["created_at"]
            }
            for d in data
        ]
        return remapped_data
    else:
        print("Error fetching data from ThingSpeak")
        return []

# Function to store data in MongoDB
def store_data_in_mongodb(data):
    if data:
        collection.insert_many(data)
        print("Data stored in MongoDB")

# Function to analyze hydration data
def analyze_hydration_data():
    cursor = collection.find()
    df = pd.DataFrame(list(cursor))

    if not df.empty:
        df['created_at'] = pd.to_datetime(df['created_at'])
        df.set_index('created_at', inplace=True)

        # Handling null values
        df.fillna(method='ffill', inplace=True)  # Forward fill for missing data

        # Convert data to appropriate types
        numeric_columns = ["Hydration Level", "Ambient Temperature", "Heart Rate", "Activity Level", "Skin Temperature", "Environmental Humidity", "Fluid Intake", "Weight"]
        df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

        # Plotting hydration data over time
        plt.figure(figsize=(12, 6))
        plt.plot(df.index, df['Hydration Level'], label='Hydration Level')
        plt.xlabel('Time')
        plt.ylabel('Hydration Level')
        plt.title('Hydration Level Over Time')
        plt.legend()
        plt.show()
# Main function
def main():
    while True:
        sensor_data = fetch_sensor_data()
        store_data_in_mongodb(sensor_data)
        analyze_hydration_data()
        time.sleep(300)  # Fetch data every 5 minutes

if __name__ == '__main__':
    main()

**Comment by Gmaya317** [comment]
# Correlation Analysis
        correlation_matrix = df[numeric_columns].corr()
        plt.figure(figsize=(10, 8))
        sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
        plt.title('Correlation Analysis')
        plt.show()

        # Summary Statistics
        print("Summary Statistics:")
        print(df[numeric_columns].describe())

        # Histograms for various measurements
        df[numeric_columns].hist(figsize=(12, 10))
        plt.suptitle('Histograms of Measurements')
        plt.show()

    else:
        print("No data available for analysis")

**Comment by Gmaya317** [comment]
import time
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pymongo import MongoClient

# ThingSpeak Channel Setup
channel_id = 2358594  # ThingSpeak channel ID
read_api_key = 'V36WZ1G9MNX31L8D'  # ThingSpeak Read API key

# MongoDB Connection Setup
uri = "mongodb+srv://luziferzacks:FH6c9Xws94Mwf4Zs@clustersmarthydration.pjdxymt.mongodb.net/?retryWrites=true&w=majority"

# Establishing a connection to MongoDB
client = MongoClient(uri)
db = client['HydrationMonitoring']  # Database name
collection = db['SensorData']  # Collection name

print("MongoDB Connected Successfully")

# Function to fetch hydration data from ThingSpeak
def fetch_sensor_data():
    url = f'https://api.thingspeak.com/channels/{channel_id}/feeds.json?api_key={read_api_key}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()['feeds']
        # Remap data to descriptive column names
        remapped_data = [
            {
                "Hydration Level": d["field1"],
                "Ambient Temperature": d["field2"],
                "Heart Rate": d["field3"],
                "Activity Level": d["field4"],
                "Skin Temperature": d["field5"],
                "Environmental Humidity": d["field6"],
                "Fluid Intake": d["field7"],
                "Weight": d["field8"],
                "created_at": d["created_at"]
            }
            for d in data
        ]
        return remapped_data
    else:
        print("Error fetching data from ThingSpeak")
        return []

# Function to store data in MongoDB
def store_data_in_mongodb(data):
    if data:
        collection.insert_many(data)
        print("Data stored in MongoDB")

# Function to analyze hydration data
def analyze_hydration_data():
    cursor = collection.find()
    df = pd.DataFrame(list(cursor))

    if not df.empty:
        df['created_at'] = pd.to_datetime(df['created_at'])
        df.set_index('created_at', inplace=True)

        # Handling null values
        df.fillna(method='ffill', inplace=True)  # Forward fill for missing data

        # Convert data to appropriate types
        numeric_columns = ["Hydration Level", "Ambient Temperature", "Heart Rate", "Activity Level", "Skin Temperature", "Environmental Humidity", "Fluid Intake", "Weight"]
        df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

        # Plotting hydration data over time
        plt.figure(figsize=(12, 6))
        plt.plot(df.index, df['Hydration Level'], label='Hydration Level')
        plt.xlabel('Time')
        plt.ylabel('Hydration Level')
        plt.title('Hydration Level Over Time')
        plt.legend()
        plt.show()

        # Correlation Analysis
        correlation_matrix = df[numeric_columns].corr()
        plt.figure(figsize=(10, 8))
        sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
        plt.title('Correlation Analysis')
        plt.show()

        # Summary Statistics
        print("Summary Statistics:")
        print(df[numeric_columns].describe())

        # Histograms for various measurements
        df[numeric_columns].hist(figsize=(12, 10))
        plt.suptitle('Histograms of Measurements')
        plt.show()

    else:
        print("No data available for analysis")

# Main function
def main():
    while True:
        sensor_data = fetch_sensor_data()
        store_data_in_mongodb(sensor_data)
        analyze_hydration_data()
        time.sleep(300)  # Fetch data every 5 minutes

if __name__ == '__main__':
    main()

**Comment by jiahaowang0906** [comment]
Who is this? Why am I keep getting notifications?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
